//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothes.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Cloth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cloth()
        {
            this.Return_clothes = new HashSet<Return_clothes>();
        }
    
        public int Id_cloth { get; set; }
        public string name { get; set; }
        public int color { get; set; }
        public int composition { get; set; }
        public int size { get; set; }
        public int supplier { get; set; }
        public int manufacturer { get; set; }
        public decimal price { get; set; }
        public System.DateTime delivery_date { get; set; }
        public System.DateTime purchase_date { get; set; }
        public byte[] photo { get; set; }

        public string CorrectDD
        {
            get
            {
                return delivery_date.ToString("D");
            }
        }
        public string CorrectPD
        {
            get
            {
                return purchase_date.ToString("D");
            }
        }

        public string CorrectColor
        {
            get
            {
                return Color1.name.ToString();
            }
        }
        public string CorrectComposition
        {
            get
            {
                return Composition1.name.ToString();
            }
        }
        public string CorrectSize
        {
            get
            {
                return Size1.name.ToString();
            }
        }
        public string CorrectSupplier
        {
            get
            {
                return Supplier1.name.ToString();
            }
        }
        public string CorrectManufacturer
        {
            get
            {
                return Manufacturer1.name.ToString();
            }
        }

        public string AdminVisibiliti
        {
            get
            {
                if (App.CurrentUser == null)
                {
                    return "Hidden";
                }
                else if (App.CurrentUser.role == 1)
                {
                    return "Hidden";
                }
                else return "Visible";
            }
        }
        public string UserVisibility
        {
            get
            {
                if (App.CurrentUser == null)
                {
                    return "Hidden";
                }
                else if (App.CurrentUser.role == 2)
                {
                    return "Hidden";
                }
                else return "Visible";
            }
        }

        public byte[] CorrectPhoto
        {
            get
            {
                if (photo == null)
                    return File.ReadAllBytes("../../Images/picture.png");
                else return photo;
            }
        }
        public virtual Color Color1 { get; set; }
        public virtual Composition Composition1 { get; set; }
        public virtual Manufacturer Manufacturer1 { get; set; }
        public virtual Size Size1 { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_clothes> Return_clothes { get; set; }
    }
}
