//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothes.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_clothes
    {
        public int Id_return { get; set; }
        public int clothes_return { get; set; }
        public int user_return { get; set; }
        public string description { get; set; }
    
        public string Correct_Clothes
        {
            get
            {
                return Cloth.Id_cloth.ToString();
            }
        }

        public string Correct_User
        {
            get
            {
                return User.Id_user.ToString();
            }
        }
        public virtual Cloth Cloth { get; set; }
        public virtual User User { get; set; }
    }
}
